# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Publish Snapshot Jar to Maven Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-snapshot-jar:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      name: ${{ steps.name.outputs.NAME }}
      version: ${{ steps.version.outputs.VERSION }}
      buildnumber: ${{ steps.buildnumber.outputs.BUILDNUMBER }}
    steps:
    - name: 'Checkout Source Code'
      uses: actions/checkout@v3

    - name: 'Read service name'
      id: name
      run: |
        NAME=$(cat settings.gradle | grep 'rootProject.name' | cut -d'=' -f2 | cut -d"'" -f2)
        echo "NAME=${NAME}" >> "$GITHUB_ENV"
        echo "NAME=${NAME}"
        echo "NAME=${NAME}" >> "$GITHUB_OUTPUT"

    - name: 'Read version'
      id: version
      run: |
        source gradle.properties
        echo "VERSION=${version}" >> "$GITHUB_ENV"
        echo "VERSION=${version}"
        echo "VERSION=${version}" >> "$GITHUB_OUTPUT"

    - name: 'Read build number'
      id: buildnumber
      run: |
        BUILDNUMBER=${{ github.run_number }}
        echo "BUILDNUMBER=${BUILDNUMBER}" >> "$GITHUB_ENV"
        echo "BUILDNUMBER=${BUILDNUMBER}"
        echo "BUILDNUMBER=${BUILDNUMBER}" >> "$GITHUB_OUTPUT"

    - name: 'Require SNAPSHOT version'
      if: ${{ ! endsWith(env.VERSION, 'SNAPSHOT') }}
      run: |
        echo "This workflow should only be triggered for SNAPSHOT builds"
        exit 1

    - name: 'Set up JDK 11'
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: 'Setup Gradle'
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0

    - name: 'Build JAR with Gradle'
      run: gradle build

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: 'Publish to GitHub Packages'
      run: gradle publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-yml:
    needs:
      - build-and-publish-snapshot-jar
    runs-on: ubuntu-latest
    steps:
      - name: 'trigger update yaml'
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.UPDATE_APPLICATION_YAML}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/stombers-senacor/application-release-yaml/actions/workflows/update-yaml.yml/dispatches \
          -d '{"ref":"main","inputs":{"artifact_name": "${{ needs.build-and-publish-snapshot-jar.outputs.name }}", "artifact_version": "${{ needs.build-and-publish-snapshot-jar.outputs.version }}", "artifact_buildnumber": "${{ needs.build-and-publish-snapshot-jar.outputs.buildnumber }}" } }'
