name: Build and Publish Snapshot Docker Image to Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-snapshot-docker-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      buildnumber: ${{ steps.buildnumber.outputs.BUILDNUMBER }}
    steps:
    - name: 'Checkout Source Code'
      uses: actions/checkout@v3

    - name: 'Read version'
      id: version
      run: |
        source gradle.properties
        echo "VERSION=${version}" >> "$GITHUB_ENV"
        echo "VERSION=${version}"
        echo "VERSION=${version}" >> "$GITHUB_OUTPUT"

    - name: 'Read build number'
      id: buildnumber
      run: |
        BUILDNUMBER=$(git rev-list main --count)
        echo "BUILDNUMBER=${BUILDNUMBER}" >> "$GITHUB_ENV"
        echo "BUILDNUMBER=${BUILDNUMBER}"
        echo "BUILDNUMBER=${BUILDNUMBER}" >> "$GITHUB_OUTPUT"
        
    - name: 'Require SNAPSHOT version'
      if: ${{ ! endsWith(env.VERSION, 'SNAPSHOT') }}
      run: |
        echo "This workflow should only be triggered for SNAPSHOT builds"
        exit 1

    - name: 'Set up JDK 11'
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: 'Setup Gradle'
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0

    - name: 'Build Container Image with Gradle'
      run: gradle bootBuildImage --imageName=ghcr.io/${{github.actor}}/githubtest.demoservice:${VERSION}-${BUILDNUMBER}

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Tag and Push Container Image'
      run: |
        echo "Publish image with tags: ${VERSION} and latest"
        docker tag ghcr.io/${{github.actor}}/githubtest.demoservice:${VERSION}-${BUILDNUMBER} ghcr.io/${{github.actor}}/githubtest.demoservice:latest
        docker push ghcr.io/${{github.actor}}/githubtest.demoservice:${VERSION}-${BUILDNUMBER}
        docker push ghcr.io/${{github.actor}}/githubtest.demoservice:latest

  run-e2e-tests:
    needs: build-and-publish-snapshot-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: 'TODO'
        run: echo "TODO run E2E Tests"

  update-yml:
    runs-on: ubuntu-latest
    steps:
      - name: 'trigger update yaml'
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.UPDATE_APPLICATION_YAML}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/stombers-senacor/application-release-yaml/actions/workflows/update-yaml.yml/dispatches \
          -d '{"ref":"main","inputs":{"artifact_name": "githubtest.demoservice", "artifact_version": ${{ needs.build-and-publish-snapshot-docker-image.outputs.version }} } }'

