name: Package files in docker image as archive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0

      - name: 'Build JAR with Gradle'
        run: gradle build

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{github.actor}}/dockerasarchive:0.0.1, ghcr.io/${{github.actor}}/dockerasarchive:latest

